[package]
name = "advent-of-code"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = "^0.3"
aoc-runner-derive = "^0.3"
nom = "^7.1"
itertools = "^0.10"
